# Generated by Django 4.1.7 on 2023-03-05 06:10

from django.db import migrations, models
import reservation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomnumber',
            new_name='room_number',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='hotel espinas', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(validators=[reservation.validators.validate_reservation_date]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(validators=[reservation.validators.validate_reservation_date]),
        ),
    ]
